<?php

namespace AppBundle\Repository;

/**
 * AuPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuPropertyRepository extends \Doctrine\ORM\EntityRepository {
    
}
