<?php

namespace AppBundle\Repository;

/**
 * AuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuRepository extends \Doctrine\ORM\EntityRepository
{
}
