<?php

namespace AppBundle\Repository;

/**
 * AuStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
