<?php

namespace AppBundle\Repository;

/**
 * BoxStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
