<?php

namespace AppBundle\Repository;

/**
 * CacheStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CacheStatusRepository extends \Doctrine\ORM\EntityRepository {
    
}
