<?php

namespace AppBundle\Repository;

/**
 * ContentProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
