<?php

namespace AppBundle\Repository;

/**
 * ContentPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentPropertyRepository extends \Doctrine\ORM\EntityRepository {
    
}
