<?php

/*
 *  This file is licensed under the MIT License version 3 or
 *  later. See the LICENSE file for details.
 *
 *  Copyright 2018 Michael Joyce <ubermichael@gmail.com>.
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Au;
use AppBundle\Entity\Deposit;
use Doctrine\ORM\EntityRepository;
use Iterator;

/**
 * DepositRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositRepository extends EntityRepository {

    /**
     * Get a query for the content items in an AU.
     *
     * @param Au $au
     *
     * @return Iterator|Deposit[]
     */
    public function auQuery(Au $au) {
        $qb = $this->createQueryBuilder('d');
        $qb->andWhere("d.au = :au");
        $qb->setParameter('au', $au);
        return $qb->getQuery()->iterate();
    }


}
