<?php

namespace AppBundle\Repository;

/**
 * DepositStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositStatusRepository extends \Doctrine\ORM\EntityRepository {
    
}
