<?php

namespace AppBundle\Repository;

/**
 * KeystoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeystoreRepository extends \Doctrine\ORM\EntityRepository {
    
}
