<?php

namespace AppBundle\Repository;

/**
 * PlnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlnRepository extends \Doctrine\ORM\EntityRepository
{
}
