<?php

namespace AppBundle\Repository;

/**
 * PluginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PluginRepository extends \Doctrine\ORM\EntityRepository {
    
}
