<?php

namespace AppBundle\Repository;

/**
 * PluginPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PluginPropertyRepository extends \Doctrine\ORM\EntityRepository {
    
}
