<?php

declare(strict_types=1);

/*
 * (c) 2021 Michael Joyce <mjoyce@sfu.ca>
 * This source file is subject to the GPL v2, bundled
 * with this source code in the file LICENSE.
 */

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Data entry form for LOCKSS plugins.
 */
class PluginType extends AbstractType
{
    /**
     * Build the form by adding types to $builder.
     */
    public function buildForm(FormBuilderInterface $builder, array $options) : void {
        $builder->add('generateManifests', ChoiceType::class, [
            'label' => 'Generate Manifests',
            'expanded' => true,
            'multiple' => false,
            'choices' => [
                'Enabled' => true,
                'Disabled' => false,
            ],
            'required' => true,
            'placeholder' => false,
            'attr' => [
                'help_block' => 'Should LOCKSSOMatic generate manifest files and set the manifest_url property on AUs?',
            ],
        ]);

        $plugin = $options['plugin'];
        $names = [];

        foreach ($plugin->getConfigPropertyNames() as $name) {
            $names[$name] = $name;
        }
        $builder->add('generatedParams', ChoiceType::class, [
            'label' => 'Generated Params',
            'expanded' => true,
            'multiple' => true,
            'choices' => $names,
            'required' => false,
            'attr' => [
                'help_block' => 'Parameters generated by LOCKSSOMatic will be ignored for matching content to AUs.',
            ],
        ]);
    }

    /**
     * Configure default options.
     */
    public function configureOptions(OptionsResolver $resolver) : void {
        $resolver->setDefaults([
            'data_class' => 'App\Entity\Plugin',
        ]);
        $resolver->setRequired([
            'plugin',
        ]);
    }
}
